### ISSUE TITLE
inference error when run own dataset with voc2007 metric

### ISSUE THREAD

**Issue by 19940312** [generalized-iou/Detectron.pytorch#2] opened 2019-04-26 08:48 UTC
## PLEASE FOLLOW THESE INSTRUCTIONS BEFORE POSTING
1. **Read the README.md thoroughly ! README.md is not a decoration.**
2. Please search existing *open and closed* issues in case your issue has already been reported
3. Please try to debug the issue in case you can solve it on your own before posting

## After following steps above and agreeing to provide the detailed information requested below, you may continue with posting your issue
(**Delete this line and the text above it.**)

### Expected results

What did you expect to see?

### Actual results

What did you observe instead?

### Detailed steps to reproduce

E.g.:

```
The command that you ran
```

### System information

* Operating system: ?
* CUDA version: ?
* cuDNN version: ?
* GPU models (for all devices if they are not all the same): ?
* python version: ?
* pytorch version: ?
* Anything else that seems relevant: ?

**Comment by 19940312** [comment] 2019-04-26 08:50
Hi, when I run this code, I convert pascal voc to coco format and evaluate it with VOC2007 metric successfully. But unfortunately I failed when I run my own dataset, i.e., NWPU VHR-10, the training process maybe correct but in the inference time, the detection result is empty. Could you give me some suggestions. Thx
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 1/390 0.258s + 0.000s (eta: 0:01:40)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 11/390 0.116s + 0.001s (eta: 0:00:44)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 21/390 0.110s + 0.001s (eta: 0:00:40)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 31/390 0.109s + 0.001s (eta: 0:00:39)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 41/390 0.107s + 0.001s (eta: 0:00:37)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 51/390 0.106s + 0.001s (eta: 0:00:36)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 61/390 0.106s + 0.001s (eta: 0:00:35)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 71/390 0.105s + 0.001s (eta: 0:00:33)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 81/390 0.106s + 0.001s (eta: 0:00:32)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 91/390 0.105s + 0.001s (eta: 0:00:31)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 101/390 0.104s + 0.001s (eta: 0:00:30)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 111/390 0.104s + 0.001s (eta: 0:00:29)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 121/390 0.103s + 0.001s (eta: 0:00:27)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 131/390 0.103s + 0.001s (eta: 0:00:26)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 141/390 0.103s + 0.001s (eta: 0:00:25)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 151/390 0.103s + 0.001s (eta: 0:00:24)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 161/390 0.104s + 0.001s (eta: 0:00:23)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 171/390 0.104s + 0.001s (eta: 0:00:22)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 181/390 0.104s + 0.001s (eta: 0:00:21)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 191/390 0.103s + 0.001s (eta: 0:00:20)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 201/390 0.103s + 0.001s (eta: 0:00:19)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 211/390 0.103s + 0.001s (eta: 0:00:18)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 221/390 0.104s + 0.001s (eta: 0:00:17)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 231/390 0.103s + 0.001s (eta: 0:00:16)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 241/390 0.103s + 0.001s (eta: 0:00:15)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 251/390 0.102s + 0.001s (eta: 0:00:14)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 261/390 0.102s + 0.001s (eta: 0:00:13)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 271/390 0.102s + 0.001s (eta: 0:00:12)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 281/390 0.102s + 0.001s (eta: 0:00:11)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 291/390 0.102s + 0.001s (eta: 0:00:10)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 301/390 0.103s + 0.001s (eta: 0:00:09)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 311/390 0.103s + 0.001s (eta: 0:00:08)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 321/390 0.103s + 0.001s (eta: 0:00:07)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 331/390 0.103s + 0.001s (eta: 0:00:06)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 341/390 0.103s + 0.001s (eta: 0:00:05)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 351/390 0.103s + 0.001s (eta: 0:00:04)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 361/390 0.103s + 0.001s (eta: 0:00:03)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 371/390 0.103s + 0.001s (eta: 0:00:01)
INFO test_engine.py: 281: im_detect: range [1, 390] of 390: 381/390 0.103s + 0.001s (eta: 0:00:00)
INFO test_engine.py: 314: Wrote detections to: /media/ailab/044414D14414C6F8/LinSheng/Experiment/Detectron_pascalVOC.pytorch/tools/Output_val/detections.pkl
INFO test_engine.py: 161: Total inference time: 48.750s
INFO task_evaluation.py:  75: Evaluating detections
INFO voc_dataset_evaluator.py:  74: Writing VOC results for: 1
INFO voc_dataset_evaluator.py:  74: Writing VOC results for: 2
INFO voc_dataset_evaluator.py:  74: Writing VOC results for: 3
INFO voc_dataset_evaluator.py:  74: Writing VOC results for: 4
INFO voc_dataset_evaluator.py:  74: Writing VOC results for: 5
INFO voc_dataset_evaluator.py:  74: Writing VOC results for: 6
INFO voc_dataset_evaluator.py:  74: Writing VOC results for: 7
INFO voc_dataset_evaluator.py:  74: Writing VOC results for: 8
INFO voc_dataset_evaluator.py:  74: Writing VOC results for: 9
INFO voc_dataset_evaluator.py:  74: Writing VOC results for: 10
INFO voc_dataset_evaluator.py: 115: VOC07 metric? Yes
Traceback (most recent call last):
  File "/media/ailab/044414D14414C6F8/LinSheng/Experiment/Detectron_pascalVOC.pytorch/tools/test_net.py", line 118, in <module>
    check_expected_results=True)
  File "/media/ailab/044414D14414C6F8/LinSheng/Experiment/Detectron_pascalVOC.pytorch/lib/core/test_engine.py", line 128, in run_inference
    all_results = result_getter()
  File "/media/ailab/044414D14414C6F8/LinSheng/Experiment/Detectron_pascalVOC.pytorch/lib/core/test_engine.py", line 108, in result_getter
    multi_gpu=multi_gpu_testing
  File "/media/ailab/044414D14414C6F8/LinSheng/Experiment/Detectron_pascalVOC.pytorch/lib/core/test_engine.py", line 163, in test_net_on_dataset
    dataset, all_boxes, all_segms, all_keyps, output_dir
  File "/media/ailab/044414D14414C6F8/LinSheng/Experiment/Detectron_pascalVOC.pytorch/lib/datasets/task_evaluation.py", line 59, in evaluate_all
    dataset, all_boxes, output_dir, use_matlab=use_matlab
  File "/media/ailab/044414D14414C6F8/LinSheng/Experiment/Detectron_pascalVOC.pytorch/lib/datasets/task_evaluation.py", line 92, in evaluate_boxes
    dataset, all_boxes, output_dir, use_matlab=use_matlab
  File "/media/ailab/044414D14414C6F8/LinSheng/Experiment/Detectron_pascalVOC.pytorch/lib/datasets/voc_dataset_evaluator.py", line 48, in evaluate_boxes
    _do_python_eval(json_dataset, salt, output_dir)
  File "/media/ailab/044414D14414C6F8/LinSheng/Experiment/Detectron_pascalVOC.pytorch/lib/datasets/voc_dataset_evaluator.py", line 125, in _do_python_eval
    use_07_metric=use_07_metric)
  File "/media/ailab/044414D14414C6F8/LinSheng/Experiment/Detectron_pascalVOC.pytorch/lib/datasets/voc_eval.py", line 179, in voc_eval
    BB = BB[sorted_ind, :]
IndexError: too many indices for array

**Comment by jgwak** [comment] 2019-04-26 22:12
I cannot help you with experiments outside of the scope of this paper. Sorry.

Closing irrelevant issue. If you believe this issue is caused by the changes I made, please feel free to reopen it with further reproducible details.

**Closed as completed by jgwak** 2019-04-26 22:12 UTC
Labels: invalid
